#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/TLS/Alert
#.build/debug/Tests/TLS/Certificate
#.build/debug/Tests/TLS/CertificateStatus
.build/debug/Tests/TLS/ChangeCipherSpec
.build/debug/Tests/TLS/ClientHello
.build/debug/Tests/TLS/ClientKeyExchange
.build/debug/Tests/TLS/ExtensionECPointFormats
.build/debug/Tests/TLS/ExtensionHeartbeat
.build/debug/Tests/TLS/ExtensionRenegotiationInfo
.build/debug/Tests/TLS/ExtensionServerName
.build/debug/Tests/TLS/ExtensionSessionTicket
.build/debug/Tests/TLS/ExtensionSignatureAlgorithms
.build/debug/Tests/TLS/ExtensionStatusRequest
.build/debug/Tests/TLS/ExtensionSupportedGroups
.build/debug/Tests/TLS/Handshake
.build/debug/Tests/TLS/Heartbeat
.build/debug/Tests/TLS/NewSessionTicket
.build/debug/Tests/TLS/Random
.build/debug/Tests/TLS/RecordLayer
.build/debug/Tests/TLS/ServerHello
.build/debug/Tests/TLS/ServerHelloDone
.build/debug/Tests/TLS/ServerKeyExchange
