#!/bin/bash

set -e

swift build

export DYLD_LIBRARY_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib/swift/macosx

.build/debug/Tests/TLS/Alert
.build/debug/Tests/TLS/Certificate
.build/debug/Tests/TLS/ChangeCipherSpec
.build/debug/Tests/TLS/ClientHello
.build/debug/Tests/TLS/ExtensionALPN
.build/debug/Tests/TLS/ExtensionExtendedMasterSecret
.build/debug/Tests/TLS/ExtensionHeartbeat
.build/debug/Tests/TLS/ExtensionKeyShare
.build/debug/Tests/TLS/ExtensionNextProtocolNegotiation
.build/debug/Tests/TLS/ExtensionPostHandshakeAuth
.build/debug/Tests/TLS/ExtensionPSKKeyExchangeModes
.build/debug/Tests/TLS/ExtensionServerName
.build/debug/Tests/TLS/ExtensionSignatureAlgorithms
.build/debug/Tests/TLS/ExtensionSupportedGroups
.build/debug/Tests/TLS/ExtensionSupportedVersions
.build/debug/Tests/TLS/Handshake
.build/debug/Tests/TLS/Heartbeat
.build/debug/Tests/TLS/NewSessionTicket
.build/debug/Tests/TLS/Random
.build/debug/Tests/TLS/Record
.build/debug/Tests/TLS/ServerHello
.build/debug/Tests/TLS/Version

.build/debug/Tests/Obsolete/CertificateStatus
.build/debug/Tests/Obsolete/ClientKeyExchange
.build/debug/Tests/Obsolete/ExtensionECPointFormats
.build/debug/Tests/Obsolete/ExtensionEncryptThenMac
.build/debug/Tests/Obsolete/ExtensionRenegotiationInfo
.build/debug/Tests/Obsolete/ExtensionSessionTicket
.build/debug/Tests/Obsolete/ExtensionStatusRequest
.build/debug/Tests/Obsolete/ServerHelloDone
.build/debug/Tests/Obsolete/ServerKeyExchange
